config/routes.rb
Rails.application.routes.draw do
  resources :musics
  devise_for :users
  root 'pages#index'

  resources :users, only: [:show, :index]
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :name, :start_event, :end_event, :location, presence: true
  validates :name, length: {minimum: 5, maximum: 50}
end

app/models/music.rb
class Music < ApplicationRecord
  has_attached_file :mp3, :storage => :cloudinary, :path => 'muvent/musics/:filename', cloudinary_resource_type: :video
  validates_attachment :mp3, :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] }, :file_name => { :matches => [/mp3\Z/] }

  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, :storage => :cloudinary, :path => 'muvent/avatar/:filename'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :first_name, :last_name, presence: true

  has_many :events, dependent: :destroy
  has_many :musics, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource

  private
    def layout_by_resource
      if devise_controller?
        "devise"
      else
        "application"
      end
    end


  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_event, except: [:index, :new, :create]

  def index
    @user = current_user
    @events = Event.where(user_id: @user).paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:success] = "Success created event."
      redirect_to events_url
    else
      flash[:danger] = "Something went wrong."
      redirect_back(fallback_location: events_url)
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Success changed event."
      redirect_to events_url
    else
      flash[:danger] = "Something went wrong."
      redirect_back(fallback_location: events_url)
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, success: "Event has been deleted."
  end

  private
    def find_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :start_event, :end_event, :location, :info)
    end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_music, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
    @musics = Music.where(user_id: @user).paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @music = current_user.musics.build
  end

  def edit
  end

  def create
    @music = current_user.musics.build(music_params)

    if @music.save
      flash[:success] = "Success added new music."
      redirect_to musics_url
    else
      flash[:danger] = "Something went wrong."
      redirect_back(fallback_location: musics_url)
    end
  end

  def update
    if @music.update(music_params)
      flash[:success] = "Success changed music."
      redirect_to musics_url
    else
      flash[:danger] = "Something went wrong."
      redirect_back(fallback_location: musics_url)
    end
  end

  def destroy
    @music.destroy
    flash[:success] = "Success deleted music."
    redirect_to musics_url
  end

  private
    def set_music
      @music = Music.find(params[:id])
    end

    def music_params
      params.require(:music).permit(:name, :mp3)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'app-lp'
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @music = Music.find(params[:id])
    @user = User.find(params[:id])
    @musics = Music.where(user_id: @user).paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name
    current_user.first_name + " " + current_user.last_name
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.haml
= simple_form_for(@event) do |f|
  %p= f.error_notification

  .row
    .col-xs-6.col-xs-offset-3
      .row
        .col-xs-12
          .form-group
            %label Event Name
            = f.input :name, input_html: {class: "form-control"}, label: false

        .col-xs-6
          .form-group
            %label Start Event
            = f.text_field :start_event, class: "form-control", id: "start_event"

        .col-xs-6
          .form-group
            %label End Event
            = f.text_field :end_event, class: "form-control", id: "end_event"

        .col-xs-12
          .form-group
            = f.input :location, input_html: {class: "form-control", rows: 4}

        .col-xs-12
          .form-group
            %label Additional Info
            = f.input :info, input_html: {class: "form-control"}, label: false

        .col-xs-12
          .form-group
            = link_to "Back", events_url, class: "btn btn-default"
            = f.button :submit, class: "btn btn-primary"

app/views/events/edit.html.haml
.row
  .col-xs-6.col-xs-offset-3
    %h1 Change Event

= render 'form'

%br/

app/views/events/index.html.erb
<h1 class="page-header">
  Your Events
  <% if @events.empty? %>
     -
    You don't have any event, create event now. <%= link_to "Create Event", new_event_url, class: "btn btn-primary" %>
  <% else %>
     -
    <%= link_to "Create Event", new_event_url, class: "btn btn-primary" %>
  <% end %>
</h1>

<div id="calendar"></div>

<br/>

<script>
  $('#calendar').fullCalendar({
    defaultView: 'month',
    header: {
      left: 'prev, next today',
      center: 'title',
      right: 'month, agendaWeek, agendaDay'
    },
    events: [
      <% @events.each do |event| %>
        {
          title: "<%= event.name %> - <%= event.location %>",
          start: "<%= event.start_event.strftime '%Y-%m-%dT%H:%M:%S' %>",
          end: "<%= event.end_event.strftime '%Y-%m-%dT%H:%M:%S' %>",
          url: "<%= event_url(event) %>"
        },
      <% end %>
    ]
  });
</script>

app/views/events/new.html.haml
.row
  .col-xs-6.col-xs-offset-3
    %h1 Create New Event

= render 'form'

%br/

app/views/events/show.html.haml
%h1 Event Detail

.row
  .col-xs-10
    .panel.panel-default
      .panel-body
        %table.row
          %tr
            %td.col-xs-4
              %h3
                %strong
                  Event Name
            %td.col-xs-4
              %h3 :
            %td.col-xs-4
              %h3
                = @event.name
          %tr
            %td.col-xs-4
              %h3
                %strong
                  Start Event
            %td.col-xs-4
              %h3 :
            %td.col-xs-4
              %h3
                = @event.start_event.strftime '%b %e %Y, %l:%M %p'
          %tr
            %td.col-xs-4
              %h3
                %strong
                  End Event
            %td.col-xs-4
              %h3 :
            %td.col-xs-4
              %h3
                = @event.end_event.strftime '%b %e %Y, %l:%M %p'
          %tr
            %td.col-xs-4
              %h3
                %strong
                  Location
            %td.col-xs-4
              %h3 :
            %td.col-xs-4
              %h3
                = @event.location
          %tr
            %td.col-xs-4
              %h3
                %strong
                  Additional Info
            %td.col-xs-4
              %h3 :
            %td.col-xs-4
              %h3
                = @event.info
          %tr
            %td.col-xs-4
              %h3
                %strong
                  Created By
            %td.col-xs-4
              %h3 :
            %td.col-xs-4
              %h3
                = @event.user.first_name
                = @event.user.last_name

= link_to "Back", events_url, class: "btn btn-default"
- if current_user == @event.user
  = link_to "Edit", edit_event_url(@event), class: "btn btn-primary"
  = link_to "Delete", event_url(@event), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"}

%br/
%br/

app/views/layouts/app-lp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muvent</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muvent</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container-fluid wrapper-custom">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>

      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muvent</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/musics/_form.html.erb
<%= simple_form_for @music, html: {multipart: true} do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="row">
        <div class="col-xs-12">
          <div class="form-group">
            <%= f.input :mp3, as: :file %>
            <p class="help-block">Format Mp3</p>
          </div>
        </div>

        <div class="col-xs-12">
          <div class="form-group">
            <%= f.input :name, input_html: {class: "form-control"} %>
          </div>
        </div>

        <div class="col-xs-12">
          <div class="form-group">
            <%= link_to 'Back', musics_path, class: "btn btn-default" %>
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/musics/edit.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <h1>Editing Music</h1>
  </div>
</div>

<%= render 'form', music: @music %>

<%= link_to 'Show', @music %>

app/views/musics/index.html.erb
<h1 class="text-center">Your Musics</h1>

<div class="row">
  <% @musics.each do |music| %>
    <div class="col-xs-6 col-xs-offset-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3 class="text-center">
            <%= link_to music.name, music_url(music) %>
          </h3>
        </div>
      </div>
    </div>
  <% end %>

  <div class="col-xs-6 col-xs-offset-3">
    <%= will_paginate @musics %>
  </div>
</div>

app/views/musics/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <h1>New Music</h1>
  </div>
</div>

<%= render 'form', music: @music %>

app/views/musics/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h2 class="text-center"><%= @music.name %></h2>

<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio">
  <div class="jp-type-single">
    <div class="jp-gui jp-interface">
      <ul class="jp-controls">
        <li><a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a></li>
        <li><a href="javascript:;" class="jp-pause" tabindex="1">&#61516;</a></li>
        <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480;</a></li>
        <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478;</a></li>
      </ul>

      <div class="jp-progress">
        <div class="jp-seek-bar">
          <div class="jp-play-bar"></div>
        </div>
      </div>

      <div class="jp-time-holder">
        <div class="jp-current-time"></div>
      </div>

      <div class="jp-volume-bar">
        <div class="jp-volume-bar-value"></div>
      </div>

      <div class="jp-no-solution">
        <span>Update Required</span>
        To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
      </div>
    </div>
  </div>
</div>

<br>
<br>
<br>

<div class="form-group text-center">
  <div class="btn-group">
    <%= link_to "Back", musics_path, class: "btn btn-default" %>
    <% if current_user == @music.user %>
      <%= link_to "Update", edit_music_path(@music), class: "btn btn-primary" %>
      <%= link_to "Delete", music_url(@music), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function(){
    $("#jquery_jplayer_1").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: "<%= @music.mp3.url %>",
        });
      },
      swfPath: "/js",
      supplied: "mp3"
    });
  });
</script>

app/views/pages/index.html.erb
<div class="banner">
  <img class="banner-img" src="<%= image_path('banner.jpeg') %>" alt="Banner">

  <nav class="cust-navbar">
    <div class="container-fluid">
      <div class="logo">
        <a href="<%= root_path %>">Muvent</a>
      </div>

      <div class="menu-list-right">
        <a href="<%= users_url %>">Explore</a>
        <% if user_signed_in? %>
          <%= link_to "Add Event", new_event_url %>
          <%= link_to "Add Music", new_music_url %>
          <%= link_to "Logout", destroy_user_session_url, method: :delete %>
        <% else %>
          <a href="<%= new_user_session_url %>">Login</a>
          <a class="menu-btn" href="<%= new_user_registration_url %>">Sign Up</a>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="wrapper-banner">
      <div class="content">
        <h1><span class="logo-content">Muvent</span> is event management and music streaming applications.</h1>
        <p>Snackwave VHS pug crucifix hot chicken mustache. Man braid taxidermy literally celiac skateboard. Etsy single-origin coffee pitchfork mumblecore. Cred normcore fingerstache cray snackwave. Retro twee salvia truffaut venmo tote bag succulents four loko fingerstache. Kombucha mumblecore hoodie viral williamsburg live-edge everyday carry shaman copper mug cronut iPhone selvage slow-carb.</p>
        <br/>
        <a href="<%= new_user_registration_url %>" class="cust-btn-default">Get Started</a>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="wrapper-section">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-3">
          <img class="img-responsive" src="<%= image_path('calendar.png') %>" alt="Calendar"/>
        </div>
        <div class="col-xs-3">
          <h3 class="text-color1">
            <strong>Event Management</strong>
          </h3>
          <p class="text-color6">Snackwave VHS pug crucifix hot chicken mustache. Man braid taxidermy literally celiac skateboard. Etsy single-origin coffee pitchfork mumblecore.</p>
        </div>
      </div>
      <br/><br/>
      <div class="row">
        <div class="col-xs-3 col-xs-offset-3">
          <h3 class="text-color1">
            <strong>Music Streaming</strong>
          </h3>
          <p class="text-color6">Snackwave VHS pug crucifix hot chicken mustache. Man braid taxidermy literally celiac skateboard. Etsy single-origin coffee pitchfork mumblecore.</p>
        </div>
        <div class="col-xs-3">
          <img class="img-responsive" src="<%= image_path('headphone.png') %>" alt="Headphone"/>
        </div>
      </div>
      <br/><br/>
      <div class="row">
        <div class="col-xs-3 col-xs-offset-3">
          <img class="img-responsive" src="<%= image_path('globe.png') %>" alt="Globe"/>
        </div>
        <div class="col-xs-3">
          <h3 class="text-color1">
            <strong>Explore More</strong>
          </h3>
          <p class="text-color6">Snackwave VHS pug crucifix hot chicken mustache. Man braid taxidermy literally celiac skateboard. Etsy single-origin coffee pitchfork mumblecore.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section-bg">
  <div class="container">
    <div class="wrapper-section">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-3">
          <h3 class="secondary-title">
            Williamsburg before they sold out 8-bit, affogato fam.
          </h3>
        </div>
        <div class="col-xs-3">
          <div class="wrapper-btn">
            <a href="<%= new_user_registration_url %>" class="cust-btn-default shadow">Get Started</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <h1 class="main-title text-center"><strong>Our Product</strong></h1>
    <br/><br/>
    <div class="row">
      <div class="col-xs-3 col-xs-offset-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="text-center">
              <div class="web">
                <i class="fa fa-desktop fa-2x"></i>
              </div>
              <h3 class="secondary-title">Muvent Web Apps</h3>
              <p>
                Tote bag pickled green juice locavore before they sold out cred
                pork belly kale chips fashion axe chartreuse street art keffiyeh
              </p>
              <a href="<%= new_user_registration_url %>" class="cust-btn-primary shadow">Get Started</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="text-center">
              <div class="mobile">
                <i class="fa fa-mobile fa-2x"></i>
              </div>
              <h3 class="secondary-title">Muvent Mobile Apps</h3>
              <p>
                Tote bag pickled green juice locavore before they sold out cred
                pork belly kale chips fashion axe chartreuse street art keffiyeh
              </p>
              <a href="#modalDownload" data-toggle="modal" class="cust-btn-primary shadow">Download</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section-bg">
  <div class="container">
    <div class="wrapper-section">
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
          <div class="text-center">
            <h3 class="secondary-title">
              Art party typewriter butcher air plant godard
              leggings cloud bread kale chips franzen
              messenger bag semiotics squid four loko
            </h3>
            <br/>
            <div class="input-group shadow">
              <input type="text" class="form-control" />
              <div class="input-group-btn">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalSubs">
                  Subscribe
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal Download -->
<div class="modal fade" id="modalDownload" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Download Files</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-12">
            <div class="text-center">
              <a href="https://drive.google.com/file/d/0BwBsRc3seSQfYnhFSU5fcV96UjQ/view?usp=sharing">
                <img src="<%= image_path('ios-android.png') %>" alt="Android" class="img-responsive">
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal Subscribe -->
<div class="modal fade" id="modalSubs" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Only placeholder, hope you enjoy it!</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%= render 'footer' %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid wrapper-custom">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Muvent</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Events <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= events_url %>">Your Events</a></li>
              <li><a href="<%= new_event_url %>">Create Event</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Musics <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= musics_url %>">Your Musics</a></li>
              <li><a href="<%= new_music_url %>">Upload Music</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= users_path %>">Explore</a></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= full_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= edit_user_registration_url %>">Edit Profile</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_url, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><a href="<%= new_user_session_url %>">Sign In</a></li>
          <li><a href="<%= new_user_registration_url %>">Sign Up</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<h1 class="text-center">Explore</h1>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-xs-6 col-xs-offset-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="media">
            <div class="media-left">
              <a href="<%= user_url(user) %>">
                <% if user.avatar.present? %>
                  <img class="media-object img-circle" width="100" height="100" src="<%= image_path user.avatar.url %>" alt="">
                <% else %>
                  <img class="media-object img-circle" width="100" height="100" src="<%= image_path('blank-user.jpg') %>" alt="Default">
                <% end %>
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= link_to "#{user.first_name} #{user.last_name}", user_url(user) %></h4>
              <h5><%= user.email %></h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= will_paginate @users %>
</div>

app/views/users/show.html.erb
<br>

<% @musics.each do |music| %>
  <h2 class="text-center"><%= music.name %></h2>

  <div id="jquery_jplayer_1" class="jp-jplayer"></div>
  <div id="jp_container_1" class="jp-audio">
    <div class="jp-type-single">
      <div class="jp-gui jp-interface">
        <ul class="jp-controls">
          <li><a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a></li>
          <li><a href="javascript:;" class="jp-pause" tabindex="1">&#61516;</a></li>
          <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480;</a></li>
          <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478;</a></li>
        </ul>

        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>

        <div class="jp-time-holder">
          <div class="jp-current-time"></div>
        </div>

        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value"></div>
        </div>

        <div class="jp-no-solution">
          <span>Update Required</span>
          To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
        </div>
      </div>
    </div>
  </div>

  <br>

  <div class="form-group text-center">
    <div class="btn-group">
      <%= link_to "Back", users_path, class: "btn btn-default" %>
      <% if current_user == @music.user %>
        <%= link_to "Update", edit_music_path(music), class: "btn btn-primary" %>
        <%= link_to "Delete", music_url(music), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
      <% end %>
    </div>
  </div>

  <br>
  <br>
  <br>
  <br>
  <br>

  <script>
    $(document).ready(function(){
      $("#jquery_jplayer_1").jPlayer({
        ready: function () {
          $(this).jPlayer("setMedia", {
            mp3: "<%= music.mp3.url %>",
          });
        },
        swfPath: "/js",
        supplied: "mp3"
      });
    });
  </script>
<% end %>